# Generated by Django 4.1.5 on 2023-06-11 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='workers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=15)),
                ('surname', models.CharField(max_length=20)),
                ('salary', models.IntegerField(default=0)),
            ],
        ),
    ]
