# Generated by Django 3.2.18 on 2023-07-05 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='note',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='todo',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
