# Generated by Django 3.2.18 on 2023-06-25 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='place',
        ),
    ]
