# Generated by Django 3.2.18 on 2023-06-25 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_order_place'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='email_name',
            new_name='email',
        ),
    ]
